### ISSUE TITLE
Comparison with PRQL

### ISSUE THREAD

**Issue by NickCrews** [wvlet/wvlet#379]
This language looks cool! What are the differences from https://prql-lang.org/?

**Comment by xerial** [comment]
@NickCrews Thank you for the pointer! PRQL does indeed look very appealing.

Here's my take on the comparison:

Syntax-wise, PRQL and Wvlet are pretty similar. 
- Wvlet is closer to SQL—for example, using "limit 10" instead of PRQL's "take 10"—but the differences are minor. 
- Wvlet favors a syntax with less parenthesis as it also targets non-data engineers. 

According to PRQL's current roadmap https://prql-lang.org/roadmap/, it appears that:

- PRQL aims to be a superior SQL replacement, offering rich editor integration (e.g., LSP support)
- It lacks a type system (for now)
   - With the knowledge of underlying types (e.g., column names) in the middle of a query, the Wvlet compiler can support operators like `shift` (moving positions of specific columns in the table) https://wvlet.org/wvlet/docs/syntax/relational-operators. It seems there is no counterpart of `shift` in PRQL.

In contrast, Wvlet's primary goals are:

- Providing a fully-typed compiler to enable advanced multi-query optimization through compiler plugins #185
- Facilitating the creation of reusable data models (e.g., a query library on GitHub) https://github.com/wvlet/wvlet/milestone/12


I hope this comparison clarifies the differences. You can also find more details of Wvlet's design philosophy here https://wvlet.org/wvlet/docs/internal/design

**Comment by NickCrews** [comment]
Thanks! The type system in Wvlet seems very compelling to me. I have some medium-technical users who I would love to give read access to our DB, but I things SQL is above their pay grade. I think Wvlet or similar is very promising for that. I'm personally not going to start depending on Wvlet yet until it become more mature, but am excited to see where it goes!

re optimization, I worry it would take mass adoption for Wvlet to get the user base to actually put in the work to write all the optimizations. Have you considered making Wvlet just the frontend, and making it serialize to [apache substrait](https://substrait.io/), then handing that off to eg [apache calcite](https://calcite.apache.org/) for the optimization? Then you get to take advantage of all that prior work.

**Comment by xerial** [comment]
> I'm personally not going to start depending on Wvlet yet until it become more mature

No worries. The project is still in its infancy, so we may need to have some breaking changes. 

> Have you considered making Wvlet just the frontend

Are you suggesting making Wvlet a frontend solely for generating SQL or Substrait IR to leverage existing SQL optimizers like Apache Calcite? I've gradually come to see this as a fast track to making Wvlet usable without investing significant effort. If we provide an interface to compile Wvlet (.wv) files into SQL in Python, Java, or Rust, we could tap into existing SQL runners, editors, and optimizers. https://github.com/wvlet/wvlet/issues/36

**Comment by NickCrews** [comment]
yes, that is what I'm suggesting, but with the caveat that I have never actually used substrait or calcite hahaha. I also guess not SOLELY a frontend, I'm sure there are other cool things that Wvlet could do, but I'm just thinking that query optimization would NOT be in the scope if I were designing this, I would try to leverage those techonologies.

**Comment by xerial** [comment]
As a starting point, Wvlet added `wvlet compile` command just for generating SQL from Wvlet queries:
https://wvlet.org/wvlet/docs/usage/cli

After that, SQL-level optimization can be performed elsewhere.

**Comment by xerial** [comment]
There is nothing more to do in this ticket. Thanks for the question
